---
- hosts: localhost
  connection: local
  become: yes
  roles:
    - { role: pacman }
    - { role: base }
    - { role: wsl }
    - { role: fonts }
    - { role: i3 }
    - { role: chrome }
    - { role: ime }
    - { role: vscode }
