---
- hosts: all
  become: yes
  vars_files:
    - ./vars/user.yml
  roles:
    - { role: pacman }
    - { role: shell }
    - { role: fonts }
    - { role: xorg }
    - { role: tigervnc }
    - { role: i3 }
    - { role: firefox }
    - { role: terminator }
    - { role: ime }
    - { role: intellij }
