---
- name: Create pacman.conf
  template:
    src: pacman.conf
    dest: /etc/pacman.conf

- name: Install pacman-contrib
  pacman:
    name: pacman-contrib
    state: present

- name: Full system upgrade
  pacman:
    update_cache: yes
    upgrade: yes
