---
- name: Install package tigervnc
  pacman:
    name: tigervnc
    state: present

- name: Install package virtual gl
  pacman:
    name: virtualgl
    state: present

- name: Push Vnc config
  copy:
    src: .vnc/
    dest: "{{ user.home }}/.vnc/"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: preserve

- name: install pexpect
  pip:
    name: pexpect
    state: present
  become: yes

- name: Config Password
  expect:
    command: "vncpasswd"
    creates: "{{ user.home }}/.vnc/passwd"
    responses:
      (?i)Password: "{{ vnc_password }}"
      (?i)Verify: "{{ vnc_password }}"
      (?i)Would you like to enter a view-only password (y/n)? : n
  become: yes
  become_user: "{{ user.name }}"

- name: Make sure a service is running
  systemd:
    state: started
    name: vncserver@:1
    enabled: yes
    scope: user
  become: yes
  become_user: "{{ user.name }}"

