---
- name: Install package chrome
  kewlfft.aur.aur:
    name:
      - google-chrome
      - chrome-remote-desktop
    state: present
  become: yes
  become_user: aur_builder 

---
- name: Copy Google Chrome Config
  template:
    src: chrome-flags.conf
    dest: "{{ user.home }}/.config/chrome-flags.conf"
  become: yes
  become_user: "{{ user.name }}"
