---
- name: Download Genie ZST
  get_url:
    url: https://github.com/arkane-systems/genie/releases/download/v1.44/genie-systemd-1.44-1-x86_64.pkg.tar.zst
    dest: /tmp/genie-systemd.pkg.tar.zst

- name: Install Daemonize
  kewlfft.aur.aur:
    use: yay
    name:
      - daemonize
    state: present
  become: yes
  become_user: aur_builder 

- name: Install Genie
  pacman:
    name: /tmp/genie-systemd.pkg.tar.zst
    state: present

- name: Enable wslg-xwayland.socket
  systemd:
    name: wslg-xwayland.socket
    enabled: yes

- name: WSL Config
  blockinfile:
    dest: '{{ user.home }}/.zshrc.local'
    block: |
      export QT_SCALE_FACTOR=2
      export GDK_SCALE=2

      if [[ ! -v INSIDE_GENIE ]]; then
          /usr/bin/genie -s
      fi
