---
- user:
    name: aur_builder
    group: wheel
- lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'

- name: Download Yay
  git:
    repo: "https://aur.archlinux.org/yay.git"
    dest: "{{ user.home }}/yay"
    force: yes
  become: yes
  become_user: "{{ user.name }}"

- name: Build Yay
  command: 
    cmd: makepkg -si --noconfirm
    creates: /usr/bin/yay
    chdir: "{{ user.home }}yay"
  become: yes
  become_user: "{{ user.name }}"
  register: yayoutput

- name: Install Aur Packages
  kewlfft.aur.aur:
    use: yay
    name: "miniconda3"
    state: present
