---
- name: Creates Config directory
  file:
    path: "{{ user.home }}/.config"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: directory

- name: Install Dotfiles
  git:
    repo: "https://github.com/ukiy6969/dotfiles.git"
    dest: "{{ user.home }}/dotfiles"
    force: yes
  register: dotfiles_status
  become: yes
  become_user: "{{ user.name }}"

- name: Link Dotfiles
  command: "{{ user.shell}} install.sh"
  args:
    chdir: "{{ user.home }}/dotfiles"
  become: yes
  become_user: "{{ user.name }}"
  when: "dotfiles_status.changed"
