---
- name: Install Zsh
  pacman:
    name: ['zsh', 'zsh-completions']
    state: present


- name: Change Shell
  user:
    name: "{{ user.name }}"
    shell: /bin/zsh
    append: yes

- name: Creates Config directory
  file:
    path: "{{ user.home }}/.config"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: directory

- name: Set Sudo No password
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    state: present
    line: "{{ user.name }} ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: yes
    validate: 'visudo -cf %s'

- include: locale.yml

- name: Install Tools
  pacman:
    name: "{{ base_packages }}"
    state: present

- include: yay.yml

- name: Install Dev tools
  pacman:
    name:
      - nodejs
    state: present

- include: neovim.yml

- include: dotfiles.yml

- name: Scala tools
  pacman:
    name: sbt
    state: present
