---
- include: locale.yml

- name: Install Tools
  pacman:
    name: "{{ base_packages }}"
    state: present

- include: user.yml

- include: aur.yml

- name: Install Dev tools
  pacman:
    name:
      - nodejs
    state: present

- include: neovim.yml

- include: dotfiles.yml

- name: Scala tools
  pacman:
    name: sbt
    state: present
