---
- name: Install Neovim
  pacman:
    name:
      - neovim
      - python-pynvim
    state: present

- name: Install Neovim
  aur:
    name:
      - python2-pynvim
      - ruby-neovim
      - nodejs-neovim
    state: present
  become: yes
  become_user: aur_builder 

- name: Install Ensime requirements
  pip:
    name:
      - websocket-client
      - sexpdata
    state: present
