---
- name: Download Yay
  git:
    repo: "https://aur.archlinux.org/yay.git"
    dest: "{{ user.home }}/yay"
    force: yes
  become: yes
  become_user: "{{ user.name }}"

- name: Build Yay
  command: makepkg -si
  become: yes
  become_user: "{{ user.name }}"
  args:
    chdir: "{{ user.home }}yay"
  register: yayoutput
