---
- name: Check is yay installed
  shell: command -v yay >/dev/null 2>&1
  register: is_yay_exist
  ignore_errors: yes
  changed_when: no

- name: Git clone Yay
  git:
    repo: "https://aur.archlinux.org/yay.git"
    dest: "{{ user.home }}/.build/yay/"
  become_user: "{{ user.name }}"
  when: is_yay_exist is failed

- name: Build Yay
  command: "makepkg -si --noconfirm"
  args:
    chdir: "{{ user.home }}/.build/yay"
    stdin: "{{ user_password }}"
    stdin_add_newline: yes
  become_user: "{{ user.name }}"
  when: is_yay_exist is failed
