---
- name: Install package fcitx
  pacman:
    name:
    - 'fcitx5'
    - 'fcitx5-mozc'
    - 'fcitx5-configtool'
    - 'fcitx5-gtk'
    - 'fcitx5-qt'
    state: present

- name: Set Input Method
  blockinfile:
    dest: /etc/environment
    block: |
      GTK_IM_MODULE=fcitx
      QT_IM_MODULE=fcitx
      XMODIFIERS=@im=fcitx
