---
- name: Install package fcitx
  pacman:
    name:
    - 'fcitx'
    - 'fcitx-mozc'
    - 'fcitx-configtool'
    state: present

- name: Set Input Method
  blockinfile:
    dest: /etc/environment
    block: |
      GTK_IM_MODULE="fcitx"
      QT_IM_MODULE="fcitx"
      XMODIFIERS='@im=fcitx'
